name: GreekOrigins
version: 1.0
author: Magister
main: com.magister.greekorigins.GreekOrigins
api-version: 1.17
commands:
  heal:
    description: Heals player to Max Health
    usage: /<command>
    aliases: [healing, healme, healmax]
  feed:
    description: Feeds player
    usage: /<command>
    aliases: [feedme, fillhunger, restorehunger]

  lvl10:
    description: Sets player level to 10
    usage: /<command>
  lvl20:
    description: Sets player level to 20
    usage: /<command>
  lvl30:
    description: Sets player level to 30
    usage: /<command>
  lvl40:
    description: Sets player level to 40
    usage: /<command>
  lvl50:
    description: Sets player level to 50
    usage: /<command>
  lvl0:
    description: Sets player level to 0
    usage: /<command>
  getlvl:
    description: Tells the player their level
    usage: /<command>

  roll:
    description: Rolls a players parent god
    usage: /<command> <player>
  addroll:
    description: Add a roll for a player
    usage: /<command>
  parent:
    description: Tells player their Godly parentt
    usage: /<command> <player>

  zeus:
    description: Sets players parent to Zeus
    usage: /<command> <player>
  poseidon:
    description: Sets players parent to Poseidon
    usage: /<command> <player>
  hades:
    description: Sets players parent to Hades
    usage: /<command> <player>
  aphrodite:
    description: Sets players parent to Aphrodite
    usage: /<command> <player>
  apollo:
    description: Sets players parent to Apollo
    usage: /<command> <player>
  ares:
    description: Sets players parent to Ares
    usage: /<command> <player>
  artemis:
    description: Sets players parent to Artemis
    usage: /<command> <player>
  athena:
    description: Sets players parent to Athena
    usage: /<command> <player>
  demeter:
    description: Sets players parent to Demeter
    usage: /<command> <player>
  dionysus:
    description: Sets players parent to Dionysus
    usage: /<command> <player>
  hephaestus:
    description: Sets players parent to Hephaestus
    usage: /<command> <player>
  hermes:
    description: Sets players parent to Hermes
    usage: /<command> <player>
  chronos:
    description: Sets players parent to Chronos
    usage: /<command> <player>

  giveWine:
    description: Gives Player Wine Item
    usage: /<command>
  giveMead:
    description: Gives Player Mead Item
    usage: /<command>